### ISSUE TITLE
Hash error - label with interpolation

### ISSUE THREAD

**Issue by SilverPhoenix99** [SilverPhoenix99/mintcs#2]
`{ "a#{1}": 3 }` throws the following error:

```
Mint.SyntaxError: (imt):1: unexpected kCOLON
   at Mint.Parse.Parser.Parse() in Mint\Solution\Mint.Parser\Parse\Parser.cs:line 54
   at Mint.Parse.Parser.Parse(String filename, String data) in Mint\Solution\Mint.Parser\Parse\Parser.cs:line 74
   at Mint.Repl.Run() in Mint\Solution\Test\Repl.cs:line 26
```

It should have returned: `{ :a1 => 3 }`

**Comment by SilverPhoenix99** [comment]
Fixed in commit https://github.com/SilverPhoenix99/mintcs/commit/d04d0a5df94206a48f86244a54362b667ee1dc5d
